### ISSUE TITLE
This is pretty stable, should you make a release tag?

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertools-image-fuzzy-developershell#17]
Let's start a milestone to point to release?

This repo is used as a build target, so it isn't that important here, but it speaks to our confidence in the image.  We can create a tagged version of the image in quay.io, when we are happy with it.

**Comment by james-nesbitt** [comment]
if it's accepted as a proposal, then I will retro-attach existing issues to the milestone

**Comment by aleksijohansson** [comment]
@james-nesbitt Great idea! I would like to tackle #7 before the release so I'll add it to the milestone.
