### ISSUE TITLE
Review of PHP7 modules may be needed

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertools-image-fuzzy-developershell#20]
I see that in the primary alpine-php image, Iler has made some php7 module changes.  We should likely parrallel those changes in this module.

In particular, he added php7-gmagick (althought I don't know why)

https://github.com/wunderkraut/alpine-php/commit/e5f0dcfd617dbe3bfe618c56bc0f5e9fb68d632c

**Comment by aleksijohansson** [comment]
It seems that there is a valid reason for someone wanting to use that with Drupal. Going to reflect the "upstream" changes in this image too. PR coming up.

**Comment by james-nesbitt** [comment]
I like the reformatted list.  We should start to do that with all images.

**Comment by james-nesbitt** [comment]
I think that this issue can be closed.

**Comment by aleksijohansson** [comment]
@james-nesbitt  I'll make a PR to the "upstream" PHP image.
