### ISSUE TITLE
Should we base the image out of wunderkraut/alpine-php?

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/wundertools-image-fuzzy-developershell#22]
I think we should base the image out of https://github.com/wunderkraut/alpine-php, but do you @james-nesbitt remember why this was not done previously? We might still need edge from alpine as the base though.

**Comment by james-nesbitt** [comment]
Previously we skipped alpine-php because:
1. we didn't want php-fpm, but rather we wanted php-cli
2. we wanted more php packages in the dev shell

**Comment by aleksijohansson** [comment]
@james-nesbitt I think 2 is not an issue, but you're right about 1. If we base this to wunderkraut/alpine-php, we would have php7-fpm which we don't need, but does it really hurt that much?

**Comment by james-nesbitt** [comment]
no it doesn't hurt.  In fact, there may even be an argument for it.

Additionally, we could always remove it in the dockerfile for devshell.

**Comment by aleksijohansson** [comment]
@james-nesbitt Good point! I'll start to work on a "rebase".

**Comment by james-nesbitt** [comment]
Merged in #25

**Comment by aleksijohansson** [comment]
Image based to wunderkraut/alpine-php in #25.
