### ISSUE TITLE
Add instructions on how to use your own .zshrc with your own theme

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/wundertools-image-fuzzy-developershell#23]
We don't want to add a fancy theme like [Powerline](https://github.com/jeremyFreeAgent/oh-my-zsh-powerline-theme) as the default shell theme in this image because it requires dependencies on the host we don't want to have, but we should add instructions on how to use your own .zshrc file to use which ever theme you like if your host prepared for it.

**Comment by james-nesbitt** [comment]
the instructions would just be about mounting/binding your own .zshrc and .oh-my-zsh ?

**Comment by james-nesbitt** [comment]
Incidentally, some other themes behave just as well as powerline, but without custom fonts etc.  There is no reason to worry about not having it.

**Comment by aleksijohansson** [comment]
@james-nesbitt We could change to candy theme, but I still think these instruction could be good for just mounting your own .zshrc.

**Comment by james-nesbitt** [comment]
agreed

**Comment by james-nesbitt** [comment]
Merged in, should be good now.  That was a good patch btw.

**Comment by aleksijohansson** [comment]
@james-nesbitt Thanks!
