### ISSUE TITLE
The "apc.enable_cli" setting should be turned on

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertools-image-fuzzy-developershell#34]
If we are using apc in this image (which we should be doing) then we will need to enable it for the cli, as this image will do mainly cli tasks.

**Comment by james-nesbitt** [comment]
Just checked, and it seems that we aren't using apc in our image because it's not available in the alpine php7 repo (testing I think)

**Comment by aleksijohansson** [comment]
@james-nesbitt I think we are using OpCache instead of APC. I'm under the impression APC is discontinued all together.

**Comment by aleksijohansson** [comment]
@james-nesbitt Please reopen this if it's still valid.
