### ISSUE TITLE
Composer is the slowest to work with

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/wundertools-image-fuzzy-developershell#38]
Saw this plugin added into the old version of WunderTools so maybe we should include it too:
https://github.com/hirak/prestissimo

**Comment by james-nesbitt** [comment]
just came here to make this issue.

**Comment by aleksijohansson** [comment]
First general fix merged. Still trying out to preload drupal composer to devshell image cache (more info in #40) to see what is the size difference compared to the speed increase with `wundertools init` command.

**Comment by james-nesbitt** [comment]
doesn't the drupal cache sit in ~/.console/cache?  if so, we are mapping in that folder from the project in the default case.

**Comment by aleksijohansson** [comment]
@james-nesbitt That's true, but I'm talking about (since I wasn't clear before) composer cache, not drupal console cache.

**Comment by aleksijohansson** [comment]
@james-nesbitt Added a PR with the changes I was talking about.

**Comment by james-nesbitt** [comment]
merged.  anything else that we can add in this issue?

**Comment by aleksijohansson** [comment]
@james-nesbitt Great! Can't come up with anything else at the moment. Should we close this for now? `wundertools init` command execution time on OS X reduced from over 9 minutes to 3 minutes with the changes so far.

**Comment by james-nesbitt** [comment]
I think that improvement means that we reached the goal of the issue.  Closing it.
