### ISSUE TITLE
Should we consider running drupal-console installation during building of this image?

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/wundertools-image-fuzzy-developershell#40]
Should we consider running drupal-console installation during building of this image so that it would cache the composer files and make initialising a Drupal project a breeze? We could just remove the installation during the build, but the cache files would be committed to the image.

**Comment by james-nesbitt** [comment]
can you specify what you mean? @aleksijohansson 

do you mean actually installing Drupal usng drupal?  You might be able to get away with just a "global requires" would could do the same thing

**Comment by aleksijohansson** [comment]
@james-nesbitt Yes, I mean actually installing Drupal using Composer, but you're right, it might just be what I'm looking for to use "global requires". I'll test it out and benchmark the `wundertools init` time between tests.

**Comment by aleksijohansson** [comment]
Continuing the work in #38. Closing this one.
