### ISSUE TITLE
Can we increase the PHP memory settings?

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertools-image-fuzzy-developershell#46]
Currently the PHP settings configure 128MB of RAM for CLI php commands.  It makes sense to increase this to better handle cases where Drush & D7 & Features are being used, which I have found typically fail due to insufficient RAM.

**Comment by aleksijohansson** [comment]
@james-nesbitt Do you know if the setting comes from the base image or is it just the default of the installed php7? Probably the latter. Anyway I think the answer to the question is yes. Changing the label to a proper issue.

**Comment by james-nesbitt** [comment]
I will try to submit a PR today.  I think that what we have is the default from PHP7 installation.

**Comment by james-nesbitt** [comment]
There is an issue in the PHP image to make it use proper settings that was never acted on https://github.com/wunderkraut/wundertools-image-fuzzy-php/issues/2
