### ISSUE TITLE
Update build to use Composer to install Drupal Console

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/wundertools-image-fuzzy-developershell#51]
Using manual installation at the moment because of dependency issues.

**Comment by aleksijohansson** [comment]
Tried again today, still doesn't work.

**Comment by james-nesbitt** [comment]
I got it to install today using this command inside a running container:

```
$/> composer global require dflydev/dot-access-configuration:dev-master psy/psysh:v0.8.0 drupal/console-core:1.0.0-rc14 drupal/console-en:1.0.0-rc14 drupal/console:1.0.0-rc14
```

Still not very pretty

**Comment by james-nesbitt** [comment]
AS the current console version is behind by 7 rc versions, and the most recent version is a large architecture refactor, we should consider doing some sort of update.

**Comment by aleksijohansson** [comment]
@james-nesbitt I have some efforts put into this in branch `20161226_update_tools`. I'll update that and put in a pull request.

**Comment by james-nesbitt** [comment]
does that branch switch to using a global composer.json, instead of a sequence of composer global require statements?

**Comment by aleksijohansson** [comment]
@james-nesbitt No it does not, but that definitely seems like a better way to do composer stuff. With composer.json we could also probably finally get rid of the dependency issues we have when using global require statements. I had to update the branch because it was not building, but I'll push it now and we can continue from there to adding a composer.json

**Comment by aleksijohansson** [comment]
The latest version 7.0.12-2 has the tools now updated.

**Comment by james-nesbitt** [comment]
this issue has been resolved.
