### ISSUE TITLE
Use composer.json instead of global composer require

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/wundertools-image-fuzzy-developershell#55]
This way we can handle the dependencies better and hopefully tackle #51 and #35

**Comment by james-nesbitt** [comment]
https://github.com/wunderkraut/image-fuzzy-alpine-devshell/issues/55 is a first run at this.

**Comment by james-nesbitt** [comment]
Unfortunately this does not fix #35

**Comment by aleksijohansson** [comment]
This is now fixed in the latest release v7.0.12-4
