### ISSUE TITLE
We should add travis to the toolset

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertools-image-fuzzy-developershell#61]
It would be nice to have travis cli in the image.

**Comment by james-nesbitt** [comment]
I'll try to go through the stack today and update the images as needed, then I will add the travis gem

**Comment by aleksijohansson** [comment]
@james-nesbitt Already started.

**Comment by james-nesbitt** [comment]
Note that https://github.com/wunderkraut/image-fuzzy-alpine-devshell/issues/62 is not really related.  that PR adds travis instructions for this repo, but this issue is about getting access to the travis cli inside containers running this image.

**Comment by james-nesbitt** [comment]
hmmm this has some breakage in master.  going to fix now.

**Comment by aleksijohansson** [comment]
Fixed in #63.
