### ISSUE TITLE
drush make requires simplexml module

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertools-image-fuzzy-developershell#72]
When running a D7 drush make, the operation fails with the following error:

```
Beginning to build site.make.                                                                                                    [ok]
PHP Fatal error:  Uncaught Error: Call to undefined function Drush\UpdateService\simplexml_load_file() in /app/.composer/vendor/drush/drush/lib/Drush/UpdateService/Project.php:74
```

I don't know what drush make needs simplexml for, but installing the php7-simplexml apk package solves the error.

**Comment by james-nesbitt** [comment]
```apk --update add php7-simplexml```

**Comment by james-nesbitt** [comment]
I've been meaning to report this for a while, but haven't had the time to get to it.

**Comment by james-nesbitt** [comment]
incoming PR, I am just testing the build first.

**Comment by james-nesbitt** [comment]
FYI, I considered adding the simplexml extension to one of the upstream builds, but if it only needed for this drush make implementation, then it shouldn't be promoted.

**Comment by james-nesbitt** [comment]
#73 should deliver a fix for this

**Comment by aleksijohansson** [comment]
Fixed in https://github.com/wunderkraut/image-fuzzy-alpine-devshell/releases/tag/v7.1.5-3.
