### ISSUE TITLE
We should probably include drush and drupal-console, even though we expect people to use project specific versions

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertools-image-fuzzy-developershell#9]
When using this image with drupal projects, we are expecting people to use project specific, composer included drush and drupal-console, but perhaps we should include globally installed standard versions, to make this image usable outside of our expectations.

This should not interfere with anyone's ability to use project specific versions

**Comment by james-nesbitt** [comment]
Something like:

```
RUN composer global require drush:drush drupal:console
```

**Comment by aleksijohansson** [comment]
@james-nesbitt Agreed!
